// js/notice-data.js
window.noticeData = [
    {
        id: 1,
        title: '㈜대도엔텍 홍보 브로슈어입니다.',
        desc: '㈜대도엔텍 홍보 브로슈어입니다.',
        date: '2025-05-19',
        views: 574,
        file: '2019Catalog대도엔텍.pdf',
        img: '/coding/images/cs/notice-view-pic.png',
    },
    // 예시 데이터 더 추가 (id는 1부터 N까지)
    {
        id: 2,
        title: '공지사항 2번 제목',
        desc: '공지사항 2번 내용입니다.',
        date: '2025-05-18',
        views: 33,
        file: '2020Catalog대도엔텍.pdf',
        img: '',
    },
    {
        id: 3,
        title: '㈜대도엔텍 가로형로고입니다.',
        desc: '㈜대도엔텍 가로형로고입니다.',
        date: '2025-05-17',
        views: 25,
        file: '/coding/images/common/logo_가로형_수정.svg',
        img: '/coding/images/common/logo_가로형_수정.svg',
    },
    {
        id: 4,
        title: '공지사항 4번 제목',
        desc: '공지사항 4번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 5,
        title: '공지사항 5번 제목',
        desc: '공지사항 5번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 6,
        title: '공지사항 6번 제목',
        desc: '공지사항 6번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 7,
        title: '공지사항 7번 제목',
        desc: '공지사항 7번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 8,
        title: '공지사항 8번 제목',
        desc: '공지사항 8번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 9,
        title: '공지사항 9번 제목',
        desc: '공지사항 9번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 10,
        title: '공지사항 10번 제목',
        desc: '공지사항 10번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 11,
        title: '공지사항 11번 제목',
        desc: '공지사항 11번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 12,
        title: '공지사항 12번 제목',
        desc: '공지사항 12번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 13,
        title: '공지사항 13번 제목',
        desc: '공지사항 13번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 14,
        title: '공지사항 14번 제목',
        desc: '공지사항 14번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 15,
        title: '공지사항 15번 제목',
        desc: '공지사항 15번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 16,
        title: '공지사항 16번 제목',
        desc: '공지사항 16번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 17,
        title: '공지사항 17번 제목',
        desc: '공지사항 17번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 18,
        title: '공지사항 18번 제목',
        desc: '공지사항 18번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 19,
        title: '공지사항 19번 제목',
        desc: '공지사항 19번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 20,
        title: '공지사항 20번 제목',
        desc: '공지사항 20번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 21,
        title: '공지사항 21번 제목',
        desc: '공지사항 21번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 22,
        title: '공지사항 22번 제목',
        desc: '공지사항 22번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 23,
        title: '공지사항 23번 제목',
        desc: '공지사항 23번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 24,
        title: '공지사항 24번 제목',
        desc: '공지사항 24번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 25,
        title: '공지사항 25번 제목',
        desc: '공지사항 25번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 26,
        title: '공지사항 26번 제목',
        desc: '공지사항 26번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 27,
        title: '공지사항 27번 제목',
        desc: '공지사항 27번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 28,
        title: '공지사항 28번 제목',
        desc: '공지사항 28번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 29,
        title: '공지사항 29번 제목',
        desc: '공지사항 29번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 30,
        title: '공지사항 30번 제목',
        desc: '공지사항 30번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 31,
        title: '공지사항 31번 제목',
        desc: '공지사항 31번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
    {
        id: 32,
        title: '공지사항 32번 제목',
        desc: '공지사항 32번 내용입니다.',
        date: '2025-05-17',
        views: 25,
        file: '',
        img: '',
    },
];
